CREATE TABLE PROFESION(
cod_prof INTEGER PRIMARY KEY,
nombre VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE PAIS(
cod_pais INTEGER PRIMARY KEY,
nombre VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE PUESTO(
cod_puesto INTEGER PRIMARY KEY,
nombre VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE DEPARTAMENTO(
cod_depto INTEGER PRIMARY KEY,
nombre VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE MIEMBRO(
cod_miembro INTEGER PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
apellido VARCHAR(100) NOT NULL,
edad INTEGER NOT NULL,
telefono INTEGER,
residencia VARCHAR(100),
PAIS_cod_pais INTEGER NOT NULL,
PROFESION_cod_prof INTEGER NOT NULL,

CONSTRAINT fk_miembro_pais FOREIGN KEY (PAIS_cod_pais) REFERENCES PAIS (cod_pais) ON DELETE CASCADE,
CONSTRAINT fk_miembro_prof FOREIGN KEY (PROFESION_cod_prof) REFERENCES PROFESION (cod_prof) ON DELETE CASCADE
);

CREATE TABLE PUESTO_MIEMBRO(
MIEMBRO_cod_miembro INTEGER NOT NULL,
PUESTO_cod_puesto INTEGER NOT NULL,
DEPARTAMENTO_cod_depto INTEGER NOT NULL,
fecha_inicio DATE NOT NULL,
fecha_fin DATE NOT NULL,

CONSTRAINT fk_puestom_miembro FOREIGN KEY (MIEMBRO_cod_miembro) REFERENCES MIEMBRO (cod_miembro) ON DELETE CASCADE,
CONSTRAINT fk_puestom_puesto FOREIGN KEY (PUESTO_cod_puesto) REFERENCES PUESTO (cod_puesto) ON DELETE CASCADE,
CONSTRAINT fk_puestom_depto FOREIGN KEY (DEPARTAMENTO_cod_depto) REFERENCES DEPARTAMENTO (cod_depto) ON DELETE CASCADE,

CONSTRAINT puesto_miembro_pk PRIMARY KEY (MIEMBRO_cod_miembro, PUESTO_cod_puesto,DEPARTAMENTO_cod_depto)
);

CREATE TABLE TIPO_MEDALLA (
cod_tipo INTEGER PRIMARY KEY,
medalla VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE MEDALLERO(
PAIS_cod_pais INTEGER NOT NULL,
cantidad_medallas INTEGER NOT NULL,
TIPO_MEDALLA_cod_tipo INTEGER NOT NULL,

CONSTRAINT fk_medallero_pais FOREIGN KEY (PAIS_cod_pais) REFERENCES PAIS (cod_pais) ON DELETE CASCADE,
CONSTRAINT fk_medallero_tipomedalla FOREIGN KEY (TIPO_MEDALLA_cod_tipo) REFERENCES TIPO_MEDALLA (cod_tipo) ON DELETE CASCADE,

CONSTRAINT medallero_pk PRIMARY KEY (TIPO_MEDALLA_cod_tipo, PAIS_cod_pais)
);

CREATE TABLE DISCIPLINA(
cod_disciplina INTEGER PRIMARY KEY,
nombre VARCHAR(50) NOT NULL,
descripcion VARCHAR(150)
);

CREATE TABLE ATLETA (
cod_atleta INTEGER PRIMARY KEY,
nombre VARCHAR(50) NOT NULL,
apellido VARCHAR(50) NOT NULL,
edad INTEGER NOT NULL,
participaciones INTEGER NOT NULL,
DISCIPLINA_cod_disciplina INTEGER NOT NULL,
PAIS_cod_pais INTEGER NOT NULL,

CONSTRAINT fk_atleta_disciplina FOREIGN KEY (DISCIPLINA_cod_disciplina) REFERENCES DISCIPLINA (cod_disciplina) ON DELETE CASCADE,
CONSTRAINT fk_atleta_pais FOREIGN KEY (PAIS_cod_pais) REFERENCES PAIS (cod_pais) ON DELETE CASCADE
);

CREATE TABLE CATEGORIA (
cod_categoria INTEGER PRIMARY KEY,
categoria VARCHAR(50) NOT NULL
);

CREATE TABLE TIPO_PARTICIPACION (
cod_participacion INTEGER PRIMARY KEY,
tipo_participacion VARCHAR(100) NOT NULL
);

CREATE TABLE EVENTO (
cod_evento INTEGER PRIMARY KEY,
fecha DATE NOT NULL,
ubicacion VARCHAR(50) NOT NULL,
hora TIME NOT NULL,
DISCIPLINA_cod_disciplina INTEGER NOT NULL,
TIPO_PARTICIPACION_cod_participacion INTEGER NOT NULL,
CATEGORIA_cod_categoria INTEGER NOT NULL,

CONSTRAINT fk_evento_disciplina FOREIGN KEY (DISCIPLINA_cod_disciplina) REFERENCES DISCIPLINA (cod_disciplina) ON DELETE CASCADE,
CONSTRAINT fk_evento_tipop FOREIGN KEY (TIPO_PARTICIPACION_cod_participacion) REFERENCES TIPO_PARTICIPACION (cod_participacion) ON DELETE CASCADE,
CONSTRAINT fk_evento_categoria FOREIGN KEY (CATEGORIA_cod_categoria) REFERENCES CATEGORIA (cod_categoria) ON DELETE CASCADE
);

CREATE TABLE EVENTO_ATLETA(
ATLETA_cod_atleta INTEGER NOT NULL,
EVENTO_cod_evento INTEGER NOT NULL,

CONSTRAINT fk_eventoat_at FOREIGN KEY (ATLETA_cod_atleta) REFERENCES ATLETA (cod_atleta) ON DELETE CASCADE,
CONSTRAINT fk_eventoat_ev FOREIGN KEY (EVENTO_cod_evento) REFERENCES EVENTO (cod_evento) ON DELETE CASCADE,

CONSTRAINT evento_atleta_pk PRIMARY KEY (ATLETA_cod_atleta, EVENTO_cod_evento)
);

CREATE TABLE TELEVISORA (
cod_televisora INTEGER PRIMARY KEY,
nombre VARCHAR(50) NOT NULL
);

CREATE TABLE COSTO_EVENTO (
EVENTO_cod_evento INTEGER NOT NULL,
TELEVISORA_cod_televisora INTEGER NOT NULL,
tarifa NUMERIC NOT NULL,

CONSTRAINT fk_costoevento_evento FOREIGN KEY (EVENTO_cod_evento) REFERENCES EVENTO (cod_evento) ON DELETE CASCADE,
CONSTRAINT fk_costoevento_televisora FOREIGN KEY (TELEVISORA_cod_televisora) REFERENCES TELEVISORA (cod_televisora) ON DELETE CASCADE,

CONSTRAINT costo_evento_pk PRIMARY KEY (EVENTO_cod_evento, TELEVISORA_cod_televisora)
);
\dt
