\d evento;
CREATE TABLE SEDE(
codigo INTEGER PRIMARY KEY,
nombre_sede VARCHAR(50) NOT NULL
);

ALTER TABLE EVENTO ALTER COLUMN ubicacion SET DATA TYPE INTEGER USING ubicacion::INTEGER;
ALTER TABLE EVENTO ADD CONSTRAINT fk_evento_sede FOREIGN KEY (ubicacion) REFERENCES SEDE(codigo) ON DELETE CASCADE;
\d sede;
\d evento;
